---
apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: mes-frontend
  labels:
    app: mes-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31200
  selector:
    app: mes-frontend

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: staging
  name: mes-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mes-frontend
    spec:
      containers:
        - name: server
          image: registry.sihe6.com/web/mes:DOCKER_TAG
          resources:
            requests:
              cpu: 0.2
              memory: 256Mi
            limits:
              cpu: 0.2
              memory: 256Mi
          ports:
            - containerPort: 80
